### ISSUE TITLE
fails causing errors on variables.

### ISSUE THREAD

**Issue by mybigman** [shmargum/vim-sass-colors#11]
can we support variables below?

```css
:root {
  --gulf-blue: 55, 64, 87;
}

rgb(var(--gulf-blue));
rgba(var(--gulf-blue), 0.5);
```

**Comment by shmargum** [comment]
support for CSS variables seems like a good idea, though I am not too familiar with them

your specific use case is a little trickier, since it's not obvious that `--gulf-blue` is a color but I think something like this should get highlighted:
```css
:root {
  --gulf-blue: rgb(55, 64, 87);
}

.class-name {
  color: var(--gulf-blue);
}
```

**Comment by mybigman** [comment]
The problem doing it like that is if I want to apply an opacity  I would have to create another variable. Where as my version can be used in both cases.

**Comment by shmargum** [comment]
I understand; however, the logic to support that would be not only complex but also computationally expensive.

For sass the rgb and rgba functions accept hex colors though, so you could have something like this:
```scss
$gulf-blue: #374057;

.class-name {
  background-color: rgba($gulf-blue, 0.5);
}
```
